### login user
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"tahenimeftah@gmail.com",
    "password": "iheb"
}

### who iam
GET http://localhost:3000/api/v1/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhaGVuaW1lZnRhaEBnbWFpbC5jb20iLCJzdWIiOiI3MTNiNTg2MC1mMzA3LTQwMzUtODIzZi0zMTY0YzBiNjEzNzUiLCJpYXQiOjE3Mjk2NDE1MTYsImV4cCI6MTcyOTY0MTU3Nn0.T2N0ELjGChGj8xu_v6BedgDS0tiCTyLgrrKb9RGm6WA
