### login user
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"tahenimeftah@gmail.com",
    "password": "iheb"
}

### who iam
GET http://localhost:3000/api/v1/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhaGVuaW1lZnRhaEBnbWFpbC5jb20iLCJzdWIiOiI0NDczYTRjMi1jNDQyLTQ1ODYtYTZjZS04MzlmMTExOTNhNTIiLCJpYXQiOjE3Mjk3MDgzNDksImV4cCI6MTcyOTcwODQwOX0.TVdy2dmbUFo8MK6u6NmLqxlwvhOGO4CL3ZX2yKb3Upw
