### create evente
POST http://localhost:3000/api/v1/evente
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNob2JhYUBnbWFpbC5jb20iLCJzdWIiOiI1YWIxNzhkYS0wMGE2LTRlYjQtOWRjNS1kMjVmYTEzMTExOWEiLCJpYXQiOjE3MzAwNzY1ODYsImV4cCI6MTczMDA3ODM4Nn0.Miv0NRHDga5WW6KEHqR249OEq03lSodGCy-gd-3HHX0

{
    "title": "sport",
    "desc": "rrrr",
    "capacity": 50,
    "location": "2024-10-28T14:35:07.123Z",
    "userId": "5ab178da-00a6-4eb4-9dc5-d25fa131119a"
}

### get eventes
GET http://localhost:3000/api/v1/evente
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNob2JhYUBnbWFpbC5jb20iLCJzdWIiOiI1YWIxNzhkYS0wMGE2LTRlYjQtOWRjNS1kMjVmYTEzMTExOWEiLCJpYXQiOjE3MzAwNzY1ODYsImV4cCI6MTczMDA3ODM4Nn0.Miv0NRHDga5WW6KEHqR249OEq03lSodGCy-gd-3HHX0

{
    "title": "string",
    "desc": "string",
    "capacity": 50,
    "location": "2024-10-28T14:35:07.123Z",
    "userId": "5ab178da-00a6-4eb4-9dc5-d25fa131119a"
}

### get one evente by id
GET http://localhost:3000/api/v1/evente/21ce0a22-d18d-4d89-9bd3-ecb8e15cf775
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNob2JhYUBnbWFpbC5jb20iLCJzdWIiOiI1YWIxNzhkYS0wMGE2LTRlYjQtOWRjNS1kMjVmYTEzMTExOWEiLCJpYXQiOjE3MzAwNzY1ODYsImV4cCI6MTczMDA3ODM4Nn0.Miv0NRHDga5WW6KEHqR249OEq03lSodGCy-gd-3HHX0
