### find all users 
GET http://localhost:3000/api/v1/users
Content-Type: application/json

### find users by id
GET http://localhost:3000/api/v1/users/4473a4c2-c442-4586-a6ce-839f11193a52
Content-Type: application/json

### create user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "firstName":"taheni",
    "lastName":"meftah",
    "email":"tahenimeftah@gmail.com",
    "phone": "23232322",
    "password": "iheb"
}
